name: Node.js App Deploy

on: 
  push:
    branch:
      main

jobs:
  deploy:
    runs-on: nodejsapp-runner
    steps:
      - name: Repository checkout 
        uses: actions/checkout@v4

      - name: Deploy app
        run: pm2 restart nodejsapp